### GET, get all users
GET http://127.0.0.1:3000//api/v1/users

### GET, get a user by id
http://127.0.0.1:3000//api/v1/users/2

### POST, create a new user
POST http://127.0.0.1:3000//api/v1/users
content-type: application/json

#### Request Body here
