### GET all products
GET http://127.0.0.1:3000//api/v1/products
### GET product by id 5
GET http://127.0.0.1:3000//api/v1/products/5

### POST, login as admin
POST http://127.0.0.1:3000//api/v1/auth/login
Content-Type: application/json

{
  "email": "samuli.lamminmaki@metropolia.fi",
  "password": "Poikanen123"
}

### POST, login as user
POST http://127.0.0.1:3000//api/v1/auth/login
Content-Type: application/json

{
  "email": "perkele@gmail.com",
  "password": "123456"
}

### POST product as admin
POST http://127.0.0.1:3000//api/v1/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3RfbmFtZSI6IlNhbXVsaSIsImxhc3RfbmFtZSI6IkxhbW1pbm3DpGtpIiwiZW1haWwiOiJzYW11bGkubGFtbWlubWFraUBtZXRyb3BvbGlhLmZpIiwicGhvbmUiOiIwNDUgNzY1IDQzMjEiLCJhZGRyZXNzIjoiSm9rdWthdHUgMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxMzQzODQwMCwiZXhwIjoxNzEzNDQyMDAwfQ.GrUlvwoYM5W9LhWijrEw31oEl5Ni3j1aNtkrLPVX4Dw

{
  "name": "Kebabruoka",
  "description": "Product 1 description",
  "price": 100,
  "category": "category 1"
}

### POST product as user
POST http://127.0.0.1:3000//api/v1/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3RfbmFtZSI6IlNhbXVsaSIsImxhc3RfbmFtZSI6IkxhbW1pbm3DpGtpIiwiZW1haWwiOiJzYW11bGkubGFtbWlubWFraUBtZXRyb3BvbGlhLmZpIiwicGhvbmUiOiIwNDUgNzY1IDQzMjEiLCJhZGRyZXNzIjoiSm9rdWthdHUgMWhoIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzE1MjQxNDY2LCJleHAiOjE3MTUyNDUwNjZ9.tQqMZmxNdvidAPJxEpCLcivX2uU45psa2-FwcSjgajQ

{
  "name": "Kebabruoka",
  "description": "Product 1 description",
  "price": 100,
  "category": "category 1"
}

### PUT product by id 1
PUT http://127.0.0.1:3000//api/v1/products/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3RfbmFtZSI6IlNhbXVsaSIsImxhc3RfbmFtZSI6IkxhbW1pbm3DpGtpIiwiZW1haWwiOiJzYW11bGkubGFtbWlubWFraUBtZXRyb3BvbGlhLmZpIiwicGhvbmUiOiIwNDUgNzY1IDQzMjEiLCJhZGRyZXNzIjoiSm9rdWthdHUgMWhoIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzE1MjQxNDY2LCJleHAiOjE3MTUyNDUwNjZ9.tQqMZmxNdvidAPJxEpCLcivX2uU45psa2-FwcSjgajQ

{
  "name": "Margherita"
}

### DELETE product by id 22
DELETE http://127.0.0.1:3000//api/v1/products/22
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3RfbmFtZSI6IlNhbXVsaSIsImxhc3RfbmFtZSI6IkxhbW1pbm3DpGtpIiwiZW1haWwiOiJzYW11bGkubGFtbWlubWFraUBtZXRyb3BvbGlhLmZpIiwicGhvbmUiOiIwNDUgNzY1IDQzMjEiLCJhZGRyZXNzIjoiSm9rdWthdHUgMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNDkwNzI2MSwiZXhwIjoxNzE0OTEwODYxfQ.2TZuX6NzIXlU9ebr--l3OS6fIB1U6VOKs2iPtMLXWXE

