### GET all products
GET http://127.0.0.1:3000//api/v1/products
### GET product by id 5
GET http://127.0.0.1:3000//api/v1/products/5

### POST, login as admin
POST http://127.0.0.1:3000//api/v1/auth/login
Content-Type: application/json

{
  "email": "samuli.lamminmaki@metropolia.fi",
  "password": "Poikanen123"
}

### POST, login as user
POST http://127.0.0.1:3000//api/v1/auth/login
Content-Type: application/json

{
  "email": "perkele@gmail.com",
  "password": "123456"
}

### POST product as admin
POST http://127.0.0.1:3000//api/v1/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3RfbmFtZSI6IlNhbXVsaSIsImxhc3RfbmFtZSI6IkxhbW1pbm3DpGtpIiwiZW1haWwiOiJzYW11bGkubGFtbWlubWFraUBtZXRyb3BvbGlhLmZpIiwicGhvbmUiOiIwNDUgNzY1IDQzMjEiLCJhZGRyZXNzIjoiSm9rdWthdHUgMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxMzQzODQwMCwiZXhwIjoxNzEzNDQyMDAwfQ.GrUlvwoYM5W9LhWijrEw31oEl5Ni3j1aNtkrLPVX4Dw

{
  "name": "Kebabruoka",
  "description": "Product 1 description",
  "price": 100,
  "category": "category 1"
}

### POST product as user
POST http://127.0.0.1:3000//api/v1/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3RfbmFtZSI6IkpvaG4iLCJsYXN0X25hbWUiOiJEb2UiLCJlbWFpbCI6InBlcmtlbGVAZ21haWwuY29tIiwicGhvbmUiOiIxMjM0NTY3ODkwIiwiYWRkcmVzcyI6IjEyMzQgTWFpbiBTdCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzEzNDM4ODIzLCJleHAiOjE3MTM0NDI0MjN9.yg4qfwMMFEIFpD5zv--aPpcERnmqDcFIQmE19-UJAWo

{
  "name": "Kebabruoka",
  "description": "Product 1 description",
  "price": 100,
  "category": "category 1"
}

### PUT product by id 5
PUT http://127.0.0.1:3000//api/v1/products/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3RfbmFtZSI6IlNhbXVsaSIsImxhc3RfbmFtZSI6IkxhbW1pbm3DpGtpIiwiZW1haWwiOiJzYW11bGkubGFtbWlubWFraUBtZXRyb3BvbGlhLmZpIiwicGhvbmUiOiIwNDUgNzY1IDQzMjEiLCJhZGRyZXNzIjoiSm9rdWthdHUgMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNDc1NjQyNywiZXhwIjoxNzE0NzYwMDI3fQ.Bl22eZCbWJXlh4HdnV3pv-a7q69ViD5ncnrx2taOQF0

{
  "name": "Margheritaa"
}

### DELETE product by id 22
DELETE http://127.0.0.1:3000//api/v1/products/22
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3RfbmFtZSI6IlNhbXVsaSIsImxhc3RfbmFtZSI6IkxhbW1pbm3DpGtpIiwiZW1haWwiOiJzYW11bGkubGFtbWlubWFraUBtZXRyb3BvbGlhLmZpIiwicGhvbmUiOiIwNDUgNzY1IDQzMjEiLCJhZGRyZXNzIjoiSm9rdWthdHUgMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNDkwNzI2MSwiZXhwIjoxNzE0OTEwODYxfQ.2TZuX6NzIXlU9ebr--l3OS6fIB1U6VOKs2iPtMLXWXE

