### GET, get all users
GET http://127.0.0.1:3000//api/v1/users

### GET, get a user by id
GET http://127.0.0.1:3000//api/v1/users/2

### POST, create a new user
POST http://127.0.0.1:3000//api/v1/users
content-type: application/json

{
  "first_name": "John",
  "last_name": "Doe",
  "email": "perkele@gmail.com",
  "phone": "1234567890",
  "address": "1234 Main St",
  "password": "123456",
  "role": "user"
}


### POST, update a user by id
POST http://127.0.0.1:3000//api/v1/users/22
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZmlyc3RfbmFtZSI6IlNhbXVsaSIsImxhc3RfbmFtZSI6IkxhbW1pbm3DpGtpIiwiZW1haWwiOiJzYW11bGkubGFtbWlubWFraUBtZXRyb3BvbGlhLmZpIiwicGhvbmUiOiIwNDUgNzY1IDQzMjEiLCJhZGRyZXNzIjoiSm9rdWthdHUgMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNDkyNzAzNywiZXhwIjoxNzE0OTMwNjM3fQ.gMu7_uKBQxnebDnbvwot2z5xMNKRX-2xmyU9K005nl4

{
  "first_name": "John",
  "last_name": "Doe"
}
